chore(gitops): apply formatting, comments, and consistency fixes across manifests
- Added YAML front matter to all kustomization.yaml files for standardization
- Commented sync-wave annotations for clarity in gitops.yaml files
- Formatted shell script in argo-cd-cluster-secret-job.yaml for readability
- Ensured consistent formatting across Helm charts and values.yaml for cert-manager, ingress-nginx, vault, and external-secrets
- Fixed indentation in k3d-bootstrap-cluster.yaml for better clarity

diff --git a/modules/vcluster/argo-cd-cluster-secret/argo-cd-cluster-secret-job.yaml b/modules/vcluster/argo-cd-cluster-secret/argo-cd-cluster-secret-job.yaml
--- a/modules/vcluster/argo-cd-cluster-secret/argo-cd-cluster-secret-job.yaml
+++ b/modules/vcluster/argo-cd-cluster-secret/argo-cd-cluster-secret-job.yaml
@@ -11,57 +11,62 @@ spec:
     spec:
       serviceAccountName: access-secrets-sa
       containers:
-      - name: configure-argocd-cluster-secret
-        image: bitnami/kubectl:latest
-        envFrom:
-        - configMapRef:
-            name: vcluster-env-vars-cm
-        command:
-        - /bin/sh
-        - -c
-        - |
-          # Wait for vcluster-kubeconfig to be available
-          while ! kubectl get secret vcluster-kubeconfig -n ${VCLUSTER_NAMESPACE} > /dev/null 2>&1; do
-            echo "Waiting for vcluster-kubeconfig secret..."
-            sleep 5
-          done
+        - name: configure-argocd-cluster-secret
+          image: bitnami/kubectl:latest
+          envFrom:
+            - configMapRef:
+                name: vcluster-env-vars-cm
+          command:
+            - /bin/sh
+            - -c
+            - |
+              # Wait for vcluster-kubeconfig to be available
+              while ! kubectl get secret vcluster-kubeconfig \
+                -n ${VCLUSTER_NAMESPACE} > /dev/null 2>&1; do
+                echo "Waiting for vcluster-kubeconfig secret..."
+                sleep 5
+              done
 
-          # Get the kubeconfig from the secret
-          KUBECONFIG_DATA=$(kubectl get secret vcluster-kubeconfig -n ${VCLUSTER_NAMESPACE} -o jsonpath='{.data.config}')
-          
-          # Decode the kubeconfig
-          KUBECONFIG=$(echo $KUBECONFIG_DATA | base64 -d)
-          
-          # Extract the token
-          TOKEN=$(echo "$KUBECONFIG" | grep 'token:' | head -n1 | awk -F'token:' '{print $2}' | xargs)
-          
-          # Create ArgoCD cluster secret
-          cat <<EOF | kubectl apply -f -
-          apiVersion: v1
-          kind: Secret
-          metadata:
-            name: ${ARGOCD_CLUSTER_SECRET_NAME}
-            namespace: kubezero
-            labels:
-              argocd.argoproj.io/secret-type: cluster
-          type: Opaque
-          stringData:
-            name: ${ARGOCD_CLUSTER_NAME}
-            server: https://vcluster.${VCLUSTER_NAMESPACE}:443
-            config: |
-              {
-                "bearerToken": "$TOKEN",
-                "tlsClientConfig": {
-                  "insecure": true
-                }
-              }
-          EOF
+              # Get the kubeconfig from the secret
+              KUBECONFIG_DATA=$(kubectl get secret vcluster-kubeconfig -n \
+                ${VCLUSTER_NAMESPACE} -o jsonpath='{.data.config}')
 
-          # Check if the secret was created successfully
-          if kubectl get secret ${ARGOCD_CLUSTER_SECRET_NAME} -n kubezero > /dev/null 2>&1; then
-            echo "Secret created successfully!"
-          else
-            echo "Failed to create the secret ${ARGOCD_CLUSTER_SECRET_NAME} in namespace kubezero" >&2
-            exit 1
-          fi
+              # Decode the kubeconfig
+              KUBECONFIG=$(echo $KUBECONFIG_DATA | base64 -d)
+
+              # Extract the token
+              TOKEN=$(echo "$KUBECONFIG" | grep 'token:' | head -n1 | \
+                awk -F'token:' '{print $2}' | xargs)
+
+              # Create ArgoCD cluster secret
+              cat <<EOF | kubectl apply -f -
+              apiVersion: v1
+              kind: Secret
+              metadata:
+                name: ${ARGOCD_CLUSTER_SECRET_NAME}
+                namespace: kubezero
+                labels:
+                  argocd.argoproj.io/secret-type: cluster
+              type: Opaque
+              stringData:
+                name: ${ARGOCD_CLUSTER_NAME}
+                server: https://vcluster.${VCLUSTER_NAMESPACE}:443
+                config: |
+                  {
+                    "bearerToken": "$TOKEN",
+                    "tlsClientConfig": {
+                      "insecure": true
+                    }
+                  }
+              EOF
+
+              # Check if the secret was created successfully
+              if kubectl get secret ${ARGOCD_CLUSTER_SECRET_NAME} \
+                -n kubezero > /dev/null 2>&1; then
+                echo "Secret created successfully!"
+              else
+                echo "Failed to create secret ${ARGOCD_CLUSTER_SECRET_NAME}" \
+                  "in namespace kubezero" >&2
+                exit 1
+              fi
       restartPolicy: OnFailure
